name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Install dependencies
      run: sudo apt update && sudo apt install libgtk-3-dev libsqlite3-dev
    - name: Build
      run: cargo build --verbose --all --release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: rs_pvw_ubuntu_x64
        path: target/release/rs_pvw

  build-win:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Install toolchain & dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gtk3 mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-toolchain mingw-w64-x86_64-rust base-devel
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all --release
    - name: Prepare Build Artifact
      run: |
        mkdir rs_pvw_windows_x64
        cp target/release/rs_pvw.exe rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libatk-1.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libbrotlicommon.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libbrotlidec.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libbz2-1.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libcairo-2.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libcairo-gobject-2.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libdatrie-1.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libepoxy-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libexpat-1.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libffi-7.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libfontconfig-1.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libfreetype-6.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libfribidi-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgcc_s_seh-1.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgdk-3-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgdk_pixbuf-2.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgio-2.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libglib-2.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgmodule-2.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgobject-2.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgraphite2.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libgtk-3-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libharfbuzz-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libiconv-2.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libintl-8.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libjpeg-8.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/liblzma-5.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libpango-1.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libpangocairo-1.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libpangoft2-1.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libpangowin32-1.0-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libpcre-1.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libpixman-1-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libpng16-16.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/librsvg-2-2.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libsqlite3-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libssp-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libstdc++-6.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libthai-0.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libwinpthread-1.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/libxml2-2.dll rs_pvw_windows_x64
        cp ../../_temp/msys/msys64/mingw64/bin/zlib1.dll rs_pvw_windows_x64
        mkdir -p rs_pvw_windows_x64/share
        cp -r ../../_temp/msys/msys64/mingw64/share/icons rs_pvw_windows_x64/share
        mkdir -p rs_pvw_windows_x64/share/glib-2.0
        cp -r ../../_temp/msys/msys64/mingw64/share/glib-2.0/schemas rs_pvw_windows_x64/share/glib-2.0
        mkdir -p rs_pvw_windows_x64/lib
        cp -r ../../_temp/msys/msys64/mingw64/lib/gdk-pixbuf-2.0 rs_pvw_windows_x64/lib
        rm rs_pvw_windows_x64/lib/gdk-pixbuf-2.0/2.10.0/loaders/*.a
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: rs_pvw_windows_x64
        path: rs_pvw_windows_x64

